version: "3"
services:
  db:
    image: mysql:5.7
    container_name: aot-management-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./cnf:/etc/mysql/conf.d
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306